export const animals = [
  {
    name: 'Betsy the Cow',
    type: 'cow',
    says: 'Mooooooo!',
    top: '370px',
    left: '50%',
    size: '100px',
  },
  {
    name: 'Noel the Donkey',
    type: 'donkey',
    says: 'Heee haw!',
    top: '300px',
    left: '36%',
    size: '80px',
  },
  {
    name: 'Golly the Goose',
    type: 'goose',
    says: 'Run pig! Be free! I would if I could.',
    top: '200px',
    left: '60%',
    size: '100px',
  },
  {
    name: 'Wilbur the Pig',
    type: 'pig',
    says: 'You have been my friend. That in itself is a tremendous thing.',
    top: '320px',
    left: '5%',
    size: '100px',
  },
  {
    name: 'Charlotte the Spider',
    type: 'spider',
    says: 'Never hurry and never worry!',
    top: '370px',
    left: '70%',
    size: '80px',
  },
  {
    name: 'Samuel the Sheep',
    type: 'sheep',
    says: "Just because we're sheep, it doesn't mean we have to follow. Think for yourselves.",
    top: '300px',
    left: '21%',
    size: '75px',
  },
];
